import React, { useEffect, useState, useMemo } from 'react';
import { UserProfile, CyclePhase, DayPlan } from '../types';
import { PHASE_COLORS, PHASE_DESCRIPTIONS } from '../constants';
import { generateDailyAdvice } from '../services/geminiService';
import { Calendar, Droplet, Zap, BookOpen, Heart, Activity, CalendarPlus, Loader2, Clock } from 'lucide-react';
import { Button } from '../components/Button';

interface DashboardProps {
  user: UserProfile;
}

export const Dashboard: React.FC<DashboardProps> = ({ user }) => {
  const [plan, setPlan] = useState<DayPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Calculate Cycle Stats
  const cycleStats = useMemo(() => {
    const lastPeriod = new Date(user.lastPeriodDate);
    const today = new Date();
    const diffTime = Math.abs(today.getTime() - lastPeriod.getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    
    // Simple Cycle Math (can be made more robust)
    const currentDay = ((diffDays - 1) % user.cycleLength) + 1;
    
    let phase = CyclePhase.MENSTRUAL;
    if (currentDay > 5 && currentDay <= 14) phase = CyclePhase.FOLLICULAR;
    else if (currentDay > 14 && currentDay <= 17) phase = CyclePhase.OVULATORY;
    else if (currentDay > 17) phase = CyclePhase.LUTEAL;

    return { currentDay, phase };
  }, [user]);

  useEffect(() => {
    const fetchPlan = async () => {
      setLoading(true);
      const result = await generateDailyAdvice(user, cycleStats.phase, cycleStats.currentDay);
      if (result) {
        setPlan({
          date: new Date().toLocaleDateString(),
          phase: cycleStats.phase,
          ...result
        });
      } else {
        setError("Could not connect to Luna's wisdom. Please check your connection.");
      }
      setLoading(false);
    };

    fetchPlan();
  }, [user, cycleStats]);

  const addToCalendar = () => {
    if (!plan || !plan.upcomingEvent) return;
    
    const today = new Date();
    const eventDate = new Date(today);
    eventDate.setDate(today.getDate() + plan.upcomingEvent.daysOffset);
    
    // Format dates as YYYYMMDD for Google Calendar
    const formatDate = (date: Date) => {
        return date.toISOString().replace(/-|:|\.\d\d\d/g, "").split("T")[0];
    };

    const dateString = formatDate(eventDate);
    // Create a generic all-day event (start date / end date+1)
    const nextDay = new Date(eventDate);
    nextDay.setDate(eventDate.getDate() + 1);
    const nextDayString = formatDate(nextDay);

    const title = `LunaSync: ${plan.upcomingEvent.title}`;
    const details = `${plan.upcomingEvent.description}\n\nGenerated by LunaSync.`;
    
    // Construct Google Calendar Link
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&details=${encodeURIComponent(details)}&dates=${dateString}/${nextDayString}`;
    window.open(url, '_blank');
  };

  const getFutureDateString = (daysOffset: number) => {
      const date = new Date();
      date.setDate(date.getDate() + daysOffset);
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
      
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Good Morning, {user.name}
          </h1>
          <p className="text-gray-500 dark:text-gray-400">Here is your cycle-synced forecast for today.</p>
        </div>
        
        <div className={`px-6 py-3 rounded-2xl border-2 flex items-center gap-3 shadow-sm ${PHASE_COLORS[cycleStats.phase]}`}>
          <div className="font-bold text-lg">{cycleStats.phase} Phase</div>
          <div className="text-sm opacity-80">Day {cycleStats.currentDay}</div>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Col: Visual & Calendar */}
        <div className="lg:col-span-1 space-y-6">
          {/* Phase Card */}
          <div className="glass rounded-3xl p-6 border border-white/50 dark:border-gray-700">
            <div className="flex justify-center mb-6 relative w-48 h-48 mx-auto">
              {/* Circular Progress Visualization */}
              <svg className="w-full h-full transform -rotate-90 origin-center" viewBox="0 0 192 192">
                {/* Background Circle */}
                <circle
                  className="text-gray-200 dark:text-gray-700"
                  strokeWidth="12"
                  stroke="currentColor"
                  fill="transparent"
                  r="90"
                  cx="96"
                  cy="96"
                />
                {/* Progress Circle */}
                <circle
                  className={`${cycleStats.phase === CyclePhase.MENSTRUAL ? 'text-rose-400' : cycleStats.phase === CyclePhase.FOLLICULAR ? 'text-violet-400' : cycleStats.phase === CyclePhase.OVULATORY ? 'text-teal-400' : 'text-amber-400'}`}
                  strokeWidth="12"
                  strokeDasharray={565}
                  strokeDashoffset={565 - (565 * cycleStats.currentDay) / user.cycleLength}
                  strokeLinecap="round"
                  stroke="currentColor"
                  fill="transparent"
                  r="90"
                  cx="96"
                  cy="96"
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                <span className="text-4xl font-bold text-gray-800 dark:text-white">{cycleStats.currentDay}</span>
                <span className="text-xs text-gray-500 uppercase tracking-wider">Cycle Day</span>
              </div>
            </div>
            
            <div className="text-center space-y-2">
              <h3 className="font-semibold text-gray-900 dark:text-white">Phase Insight</h3>
              <p className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed">
                {PHASE_DESCRIPTIONS[cycleStats.phase]}
              </p>
            </div>
          </div>

          {/* Upcoming Events Card */}
          <div className="glass rounded-3xl p-6 border border-white/50 dark:border-gray-700 flex flex-col gap-4">
             <h3 className="font-bold text-gray-900 dark:text-white flex items-center gap-2">
               <Calendar size={20} /> Upcoming
             </h3>
             
             {/* AI Suggested Event */}
             <div className="space-y-3">
                {loading ? (
                    <div className="p-4 rounded-xl bg-white/50 dark:bg-gray-800/50 animate-pulse">
                        <div className="h-4 bg-gray-200 rounded w-3/4 mb-2"></div>
                        <div className="h-3 bg-gray-200 rounded w-full"></div>
                    </div>
                ) : plan?.upcomingEvent ? (
                    <div className="p-4 rounded-xl bg-gradient-to-br from-white/80 to-white/40 dark:from-gray-800/80 dark:to-gray-800/40 border border-pink-100 dark:border-gray-600 shadow-sm">
                        <div className="flex justify-between items-center mb-3">
                           <span className="text-xs font-bold px-2 py-1 rounded-md bg-pink-100 text-pink-600 dark:bg-pink-900/40 dark:text-pink-300 uppercase tracking-wider flex items-center gap-1">
                             <Clock size={10} /> {getFutureDateString(plan.upcomingEvent.daysOffset)}
                           </span>
                           <span className="text-xs text-gray-400">In {plan.upcomingEvent.daysOffset} days</span>
                        </div>
                        
                        <h4 className="font-bold text-gray-800 dark:text-gray-100 mb-2 text-base">
                            {plan.upcomingEvent.title}
                        </h4>
                        
                        <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed line-clamp-4">
                            {plan.upcomingEvent.description}
                        </p>
                    </div>
                ) : null}
             </div>
             
             {plan?.upcomingEvent && (
                <Button variant="outline" onClick={addToCalendar} className="w-full text-sm py-2 group hover:border-pink-400 hover:text-pink-500 dark:hover:text-pink-400">
                  <CalendarPlus size={16} className="group-hover:scale-110 transition-transform" /> Add to Calendar
                </Button>
             )}
          </div>
        </div>

        {/* Right Col: AI Recommendations */}
        <div className="lg:col-span-2 space-y-6">
          
          {loading ? (
             <div className="h-96 glass rounded-3xl flex flex-col items-center justify-center text-gray-500 animate-pulse">
                <Loader2 className="animate-spin mb-4" size={48} />
                <p>Consulting holistic experts...</p>
             </div>
          ) : error ? (
             <div className="h-64 glass rounded-3xl flex items-center justify-center text-red-500">
                {error}
             </div>
          ) : plan ? (
            <>
              {/* Summary Hero */}
              <div className="glass rounded-3xl p-8 border-l-8 border-l-indigo-400 dark:border-l-indigo-500 relative overflow-hidden">
                 <div className="absolute top-0 right-0 p-4 opacity-10">
                    <Zap size={100} />
                 </div>
                 <h2 className="text-2xl font-bold mb-2 text-gray-900 dark:text-white">Daily Focus</h2>
                 <p className="text-lg text-gray-700 dark:text-gray-200 italic">"{plan.summary}"</p>
                 <div className="mt-4 flex items-center gap-2 text-sm font-semibold text-indigo-600 dark:text-indigo-400">
                    <Activity size={16} /> Mood Forecast: {plan.moodForecast}
                 </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Productivity */}
                <div className="glass rounded-3xl p-6 hover:scale-[1.02] transition-transform duration-300">
                   <div className="flex items-center gap-3 mb-4">
                      <div className="p-3 rounded-full bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300">
                         <BookOpen size={24} />
                      </div>
                      <h3 className="font-bold text-lg">Work & Study</h3>
                   </div>
                   <p className="text-gray-600 dark:text-gray-300">{plan.productivityHack}</p>
                </div>

                {/* Workout */}
                <div className="glass rounded-3xl p-6 hover:scale-[1.02] transition-transform duration-300">
                   <div className="flex items-center gap-3 mb-4">
                      <div className="p-3 rounded-full bg-orange-100 text-orange-600 dark:bg-orange-900 dark:text-orange-300">
                         <Activity size={24} />
                      </div>
                      <h3 className="font-bold text-lg">Movement</h3>
                   </div>
                   <p className="text-gray-600 dark:text-gray-300">{plan.workoutRecommendation}</p>
                </div>

                {/* Nutrition */}
                <div className="glass rounded-3xl p-6 hover:scale-[1.02] transition-transform duration-300">
                   <div className="flex items-center gap-3 mb-4">
                      <div className="p-3 rounded-full bg-green-100 text-green-600 dark:bg-green-900 dark:text-green-300">
                         <Droplet size={24} />
                      </div>
                      <h3 className="font-bold text-lg">Nutrition</h3>
                   </div>
                   <p className="text-gray-600 dark:text-gray-300">{plan.nutritionTip}</p>
                </div>

                {/* Self Care */}
                <div className="glass rounded-3xl p-6 hover:scale-[1.02] transition-transform duration-300">
                   <div className="flex items-center gap-3 mb-4">
                      <div className="p-3 rounded-full bg-pink-100 text-pink-600 dark:bg-pink-900 dark:text-pink-300">
                         <Heart size={24} />
                      </div>
                      <h3 className="font-bold text-lg">Self Care</h3>
                   </div>
                   <p className="text-gray-600 dark:text-gray-300">{plan.selfCareAction}</p>
                </div>
              </div>
            </>
          ) : null}

        </div>
      </div>
    </div>
  );
};